apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    name: harbor

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.16.0
    helm:
      releaseName: harbor
      valuesObject:
        externalURL: "https://registry.solufit.net"
        expose:
          ingress:
            hosts:
              core: "registry.solufit.net"
              
      persistence:
        persistentVolumeClaim:
          registry:
            accessMode: ReadWriteMany
          jobservice:
            accessMode: ReadWriteMany
          database:
            accessMode: ReadWriteOnce
          


  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor