apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    name: portainer

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: 1.0.59
    helm:
      releaseName: portainer
      valuesObject:
        service:
          type: ClusterIP
        persistence:
          storageClass: "local-path"
          size: "5Gi"
        ingress:
          enabled: true
          className: cloudflare-tunnel
          hosts:
            - host: "manager.solufit.net"
              paths:
              - path: "/portainer/"
                pathType: Prefix

  destination:
    server: "https://kubernetes.default.svc"
    namespace: podinfo