apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    name: portainer

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    chart: portainer
    repoURL: https://portainer.github.io/k8s/
    targetRevision: 1.0.59
    helm:
      releaseName: portainer
      valuesObject:
        service:
          type: ClusterIP
        persistence:
          storageClass: "local-path"
          size: "5Gi"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "cloudflare-tunnel"
          hosts:
            - host: "manager-portainer.solufit.net"
              paths:
              - path: "/"
                pathType: Prefix

  destination:
    server: "https://kubernetes.default.svc"
    namespace: portainer