apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
    helm:
      releaseName: longhorn
      valuesObject:
        service.ui.type: Rancher-Proxy
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          reclaimPolicy: Retain
        longhornUI.replicas: 1
        csi:
          # -- kubelet root directory. When unspecified, Longhorn uses the default value.
          kubeletRootDir: ~
          # -- Replica count of the CSI Attacher. When unspecified, Longhorn uses the default value ("3").
          attacherReplicaCount: "4"
          # -- Replica count of the CSI Provisioner. When unspecified, Longhorn uses the default value ("3").
          provisionerReplicaCount: "4"
          # -- Replica count of the CSI Resizer. When unspecified, Longhorn uses the default value ("3").
          resizerReplicaCount: "4"
          # -- Replica count of the CSI Snapshotter. When unspecified, Longhorn uses the default value ("3").
          snapshotterReplicaCount: "1"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system