apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    name: longhorn-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
    helm:
      releaseName: longhorn
      valuesObject:
        csi.attacherReplicaCount: 2
        csi.resizerReplicaCount: 2
        csi.snapshotterReplicaCount: 2
        service.ui.type: Rancher-Proxy
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          reclaimPolicy: Retain
        longhornUI.replicas: 1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system