apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
  labels:
    name: podinfo

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.7.1
    helm:
      releaseName: podinfo
      valuesObject:
        ingress:
          enabled: true
          className: cloudflare-tunnel
          hosts:
            - host: podinfo.solufit.net
              paths:
                - /
          
  destination:
    server: "https://kubernetes.default.svc"
    namespace: podinfo