# https://qiita.com/takuya_0301/items/2f96837e331120e88a26
# https://qiita.com/takuya_0301/items/428d2fb9365ede8b873e

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    chart: oci-secrets-store-csi-driver-provider
    repoURL: https://oracle.github.io/oci-secrets-store-csi-driver-provider/charts
    targetRevision: 0.4.1
    helm:
      releaseName: oci-secrets-store
      valuesObject:
        secrets-store-csi-driver.syncSecret.enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system