apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd

data:
   url: https://manager.solufit.net
   oidc.config: |
         name: Azure
         issuer: https://login.microsoftonline.com/d00b930f-76f8-4f95-92c6-922f9cca19b4/v2.0
         clientID: d2a360e0-8db7-4f70-be32-5fd0667dbe13
         clientSecret: $oidc.azure.clientSecret
         requestedIDTokenClaims:
            groups:
               essential: true
               value: "SecurityGroup"
         requestedScopes:
            - openid
            - profile
            - email