apiVersion: v1
data:
  policy.csv: |
    g, yuuta.takahashi@solufit.net, role:admin
  scopes: '[email]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd