apiVersion: v1
kind: Namespace
metadata:
  name: nfs-system
  labels:
    name: nfs-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL:  https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.2
    helm:
      releaseName: rancher
      valuesObject:
        replicaCount: 2
        nfs:
          server: "10.100.0.9"
          path: "/mnt/export"
        storageClassName:
          defaultClass: true
          reclaimPolicy: Retain
          accessModes: ReadWriteMany

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
