apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    chart: k8s-monitoring
    repoURL:  https://grafana.github.io/helm-charts
    targetRevision: 2.0.18
    helm:
      releaseName: alloy
      valuesObject:
        cluster:
          name: logging-cluster
        destinations:
          - name: loki
            type: loki
            url: http://loki-gateway/loki/api/v1/push
        clusterEvents:
          enabled: true
          collector: alloy-logs
          namespaces: [] # all
        nodeLogs:
          enabled: false
        podLogs:
          enabled: true
          gatherMethod: kubernetesApi
          collector: alloy-logs
          labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
          structuredMetadata:
            pod: pod  # Set structured metadata "pod" from label "pod"
          namespaces: [] # all
        # Collectors
        alloy-singleton:
          enabled: false
        alloy-metrics:
          enabled: false
        alloy-logs:
          enabled: true
          alloy:
            mounts:
              varlog: false
            clustering:
              enabled: true
        alloy-profiles:
          enabled: false
        alloy-receiver:
          enabled: false

  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
