apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-azure-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault
  target:
    name: grafana-azure-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: grafana-azure-client-id
    - secretKey: client-secret
      remoteRef:
        key: grafana-azure-client-secret
    - secretKey: tenant-id
      remoteRef:
        key: grafana-azure-tenant-id
