apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.5.0
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheusOperator:
          createCustomResource: true
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "longhorn"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: "5Gi"
        grafana:
          adminPassword: "admin"
          persistence:
            enabled: true
            type: pvc
            storageClassName: "longhorn"
            size: "5Gi"
          ingress:
            enabled: true
            hosts: ["grafana.solufit.net"]
            path: "/"


  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring