apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  source:
    chart: rancher-monitoring
    repoURL: https://charts.rancher.io
    targetRevision: v0.75.1
    helm:
      releaseName: rancher-monitoring
      valuesObject:
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "nfs-client"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: "50Gi"
        grafana:
          adminPassword: "admin"
          persistence:
            enabled: true
            type: sts
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            size: "10Gi"
            finalizers:
              - kubernetes.io/pvc-protection
          ingress:
            enabled: true
            hosts: ["grafana.solufit.net"]
            path: "/"
          grafana.ini:
            paths:
              data: /var/lib/grafana/
              logs: /var/log/grafana
              plugins: /var/lib/grafana/plugins
              provisioning: /etc/grafana/provisioning
            analytics:
              check_for_updates: true
            log:
              mode: console
            grafana_net:
              url: https://grafana.net
            server:
              domain: "grafana.solufit.net"
              root_url: "https://grafana.solufit.net/"


  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
