apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.1.1
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheus-node-exporter:
          nameOverride: "node-exporter"
          podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
            jobLabel: node-exporter
            app.kubernetes.io/name: node-exporter

          prometheus:
            monitor:
              enabled: false
              
            podMonitor:
              enabled: true
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "nfs-client"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: "50Gi"
        grafana:
          initChownData:
            enabled: false
          adminPassword: "admin"

          datasources:
            datasources.yaml:
                  apiVersion: 1
                  datasources:
                  - name: Loki
                    type: loki
                    access: proxy
                    orgId: 1
                    url: http://loki-gateway:80
                    basicAuth: false
                    isDefault: false
                    version: 1
                    editable: false
          persistence:
            enabled: true
            type: sts
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            size: "10Gi"
            finalizers:
              - kubernetes.io/pvc-protection
          ingress:
            enabled: true
            hosts: ["grafana.solufit.net"]
            path: "/"
          grafana.ini:
            paths:
              data: /var/lib/grafana/
              logs: /var/log/grafana
              plugins: /var/lib/grafana/plugins
              provisioning: /etc/grafana/provisioning
            analytics:
              check_for_updates: true
            log:
              mode: console
            grafana_net:
              url: https://grafana.net
            server:
              domain: "grafana.solufit.net"
              root_url: "https://grafana.solufit.net/"


  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
