apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.1.1
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        kube-state-metrics:
          prometheus:
            monitor:
              enabled: false

          service:
            annotations:
              app.kubernetes.io/instance : kube-prometheus-stack

        prometheus-node-exporter:
          nameOverride: "node-exporter"
          podLabels:
    ## Add the 'node-exporter' label to be used by serviceMonitor to match standard common usage in rules and grafana dashboards
            jobLabel: node-exporter
            app.kubernetes.io/name: node-exporter

          prometheus:
            monitor:
              enabled: false
              
            podMonitor:
              enabled: true
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "nfs-client"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: "50Gi"
        grafana:
          initChownData:
            enabled: false
          adminPassword: "admin"

          datasources:
            datasources.yaml:
                  apiVersion: 1
                  datasources:
                  - name: Loki
                    type: loki
                    access: proxy
                    orgId: 1
                    url: http://loki-gateway:80
                    basicAuth: false
                    isDefault: false
                    version: 1
                    editable: false
          persistence:
            enabled: true
            type: sts
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            size: "10Gi"
            finalizers:
              - kubernetes.io/pvc-protection
          ingress:
            enabled: true
            hosts: ["grafana.solufit.net"]
            path: "/"
          grafana.ini:
            paths:
              data: /var/lib/grafana/
              logs: /var/log/grafana
              plugins: /var/lib/grafana/plugins
              provisioning: /etc/grafana/provisioning
            analytics:
              check_for_updates: true
            log:
              mode: console
            grafana_net:
              url: https://grafana.net
            server:
              domain: "grafana.solufit.net"
              root_url: "https://grafana.solufit.net/"
            # auth.azuread:
            #   name: Solufit Azure AD
            #   enabled: false
            #   client_authentication: "client_secret_post"
            #
            #   allow_sign_up: true
            #   auto_login: false
            #
            #   # Reference: https://grafana.com/docs/grafana/latest/auth/azuread/
            #   # Please refer the following document to use secret
            #   # https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#how-to-securely-reference-secrets-in-grafanaini
            #   client_id: "client_id"
            #   client_secret: "client_secret"
            #   scope: "openid email profile"
            #   auth_url: "https://login.microsoftonline.com/tenant_id/oauth2/v2.0/authorize"
            #   token_url: "https://login.microsoftonline.com/tenant_id/oauth2/v2.0/token"
            #   use_pkce: true




  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
