apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL:  https://grafana.github.io/helm-charts
    targetRevision: 6.28.0
    helm:
      releaseName: loki
      valuesObject:
        loki:
          auth_enabled: false
          singleBinary:
            persistence:
              enabled: true
              storageClassName: "nfs-client"
          commonConfig:
            replication_factor: 3
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          pattern_ingester:
              enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
          ruler:
            enable_api: true

        minio:
          enabled: true
          persistence:
            annotations:
              "volume.beta.kubernetes.io/storage-class": "nfs-client"

        deploymentMode: SingleBinary

        singleBinary:
          replicas: 3
          persistence:
            enabled: true
            storageClass: "nfs-client"
            size: 10Gi


        chunksCache:
          enabled: false

        # Zero out replica counts of other deployment modes
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0


  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Retry=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
