apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 3
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.9.0
    helm.sh/chart: prometheus-node-exporter-4.44.1
    release: kube-prometheus-stack
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:release: {}
        f:spec:
          f:attachMetadata:
            f:node: {}
          f:endpoints: {}
          f:jobLabel: {}
          f:selector: {}
      manager: argocd-controller
      operation: Apply
  name: kube-prometheus-stack-prometheus-node-exporter
  namespace: monitoring
spec:
  attachMetadata:
    node: false
  endpoints:
    - port: http-metrics
      scheme: http
      path: /metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: prometheus-node-exporter