apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  generation: 2
  labels:
    jobLabel: node-exporter
    release: node-exporter
  managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:jobLabel: {}
            f:release: {}
        f:spec:
          f:attachMetadata:
            f:node: {}
          f:jobLabel: {}
          f:namespaceSelector:
            f:matchNames: {}
          f:podMetricsEndpoints: {}
          f:selector: {}
      manager: argocd-controller
      operation: Apply
  name: node-exporter
  namespace: monitoring
spec:
  attachMetadata:
    node: false
  jobLabel: node-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  podMetricsEndpoints:
    - enableHttp2: false
      filterRunning: true
      followRedirects: false
      honorLabels: true
      honorTimestamps: true
      path: /metrics
      port: http-metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-prometheus-stack
      app.kubernetes.io/name: prometheus-node-exporter