apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    name: cattle-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    chart: rancher
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.10.1
    helm:
      releaseName: rancher
      valuesObject:
        hostname: "manager-rancher.solufit.net"
        replicas: 1
        ingress:
          enabled: true
          tls.source: "rancher"
          hosts:
            - host: "manager-rancher.solufit.net"
              paths:
              - path: "/"
                pathType: Prefix

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cattle-system